var palestrantes = [{
	"nome" : "Diego Eis",
	"twitter" : "@diegoeis",
	"palestra", "",
	"foto":"images/diego.jpg",
	"linkTwitter" : "http://twitter.com/diegoeis/" ,
	"bio" : "Criador do Tableless.com.br, website que ajudou a disseminar o desenvolvimento inteligente com Padrões Web no Brasil. Palestrante e evangelista sobre boas práticas no desenvolvimento client-side. Como consultor já atendeu equipes e gerentes de empresas como Google, Globo.com, iG, Yahoo!, UOL, Universidade Uninove e outros. É também colunista da Revista Wide e revisor técnico da editora Bookman. Atualmente é Coordenador da equipe de front-end na Locaweb." ,
},
{
	"nome" : "Edu Agni" ,
	"twitter" : "@eduagni",
	"palestra", "O papel do Front-End na Experiência do Usuário",
	"foto":,
	"linkTwitter" : ,
	"bio" : '<strong><a href="http://www.uxdesign.blog.br">Edu</a></strong> é UX Designer no iMasters, curador da área de design da Campus Party Brasil e professor dos cursos de Direção de arte da SAIBADESIGN. Trabalha há nove anos com projetos nas áreas de usabilidade, interfaces, interação, criação e web standards.' ,
},
{
	"nome" : ,
	"twitter" : ,
	"palestra", "",
	"foto":,
	"linkTwitter" : ,
	"bio" : ,
},
{
	"nome" : ,
	"foto":,
	"palestra", "",
	"twitter" : ,
	"linkTwitter" : ,
	"bio" : ,
}]